version: '3'
services:
  hugo:
    image: klakegg/hugo:latest
    volumes:
      - .:/src
    ports:
      - 1313:1313
    command: server --baseUrl="https://${CODESPACE_NAME}-1313.app.github.dev" --appendPort=false
