orbs:
  hugo: circleci/hugo@1.2.2
version: 2.1
workflows:
  main:
    jobs:
      - hugo/build:
          source: site/
          hugo-extra-flags: "--themesDir ../.. --gc --theme project"
          html-proofer: false
