name: Build And Deploy

on:
  push:
    branches:
      - main  # Set a branch to deploy
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2
#        with:
#          submodules: true  # Fetch Hugo themes (true OR recursive)
#          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.92.0'
          # extended: true

      - name: Build
        run: hugo -v -s site/ -d public --themesDir ../.. --gc --theme meghna-hugo

      - name: SFTP uploader
        uses: wangyucode/sftp-upload-action@v1.1
        with:         
          host: sftp.edu.hu         
          username: mvdiakotthon.edu.hu
          password: ${{ secrets.SFTP_PASSWORD }}
          localDir: site/static/placeholders
          remoteDir: www
        # dryRun: # optional
