name: Build and deploy to KIFU

on:
  # Runs on pushes targeting the default branch, releases: 1.*
  push:
    tags:        
      - 1.*

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
# permissions:
#   contents: read
#   pages: write
#   id-token: write

# Allow one concurrent deployment
concurrency:
  group: "deploy-to-kifu"
  cancel-in-progress: true

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  # Deploy to KIFÜ
  deploy-to-kifu:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: FTP Deployer to KIFU
        id: deployment-to-kifu
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
            username: ${{ secrets.FTP_USERNAME }}
            server: ${{ secrets.FTP_HOST }}
            port: ${{ secrets.FTP_PORT }}
            local_path: './kifu_placeholder'
            remote_path: 'www/test'
            sftp_only: true
            password: ${{ secrets.FTP_PASSWORD }}
